sudo: false

language: php

php:
    - 5.5

before_install:
    - composer self-update

install:
    - composer install --no-interaction

script:
    - vendor/bin/phpcs --standard=PSR1,PSR2 src
    - vendor/bin/phpmd src text cleancode,codesize,design
    - vendor/bin/phpspec run
